version: '3'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      SERVICES: lambda,sqs,s3,apigateway
      DATA_DIR: /tmp/localstack/data
      PROVIDER_OVERRIDE_S3: asf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack
    networks:
      - localstack-net

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  localstack-net:

